name: Alphadoc API upload
description: Upload and Publish OpenAPI specs in alphadoc

inputs:
  OPENAPI_FILE:
    description: "Relative path to the OpenAPI file from the root of your repo"
    required: true
  ORGANISATION:
    description: "Alphadoc organisation name, subdomain of your url."
    required: true
  PROJECT_ID:
    description: "Alphadoc Project ID"
    required: true
  DOCUMENT_ID:
    description: "Alphadoc Document ID"
    required: true
  APIKEY:
    description: "API Key to authenticate the request"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Convert JSON to base64
      shell: bash
      run: |
        base64_file=$(base64 -w 0 ${{ inputs.OPENAPI_FILE }})
        echo "base64=$base64_file" >> $GITHUB_ENV

    - name: Upload OpenAPI and get versionId
      shell: bash
      run: |
        version_response=$(curl -f -s -X POST \
          -H "X-API-KEY: ${{ inputs.APIKEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "document": "${{ env.base64 }}",
            "documentType": "application/json"
          }' \
          "https://${{ inputs.ORGANISATION }}.alphadoc.io/v1/documents/${{ inputs.DOCUMENT_ID }}/versions")
        version_id=$(echo "$version_response" | jq -r '.id')
        echo "versionId=$version_id" >> $GITHUB_ENV

    - name: Publish document
      shell: bash
      run: |
        curl -f -s -X PATCH \
          -H "X-API-KEY: ${{ inputs.APIKEY }}" \
          -H "Content-Type: application/json" \
          "https://${{ inputs.ORGANISATION }}.alphadoc.io/v1/documents/${{ inputs.DOCUMENT_ID }}/versions/${{ env.versionId }}/publish"
