name: Upload and publish new openapi

on:
  pull_request:
    branches: [main]

jobs:
  upload_and_send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload new API version
        uses: alphadoc-io/action-update-api@v1
        with:
          OPENAPI_FILE: "test-openapi.json"
          ORGANISATION: ${{ vars.ALPHADOC_ORGANISATION }}
          PROJECT_ID: ${{ vars.ALPHADOC_PROJECT_ID }}
          DOCUMENT_ID: ${{ vars.ALPHADOC_DOCUMENT_ID }}
          APIKEY: ${{ secrets.ALPHADOC_APIKEY }}
